version: '3.4'
services:

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  db:
    build: db
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - postgres

  elasticsearch:
    image: elasticsearch:8.6.2
    restart: always
    environment:
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms1000m -Xmx1000m'
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/opt/elasticsearch/data
    ports:
      - '9200:9200'
    env_file:
      - ./.env
    depends_on:
      - postgres

  etl:
    build: ./postgres_to_es
    restart: always
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
      - postgres

  fastapi:
    build: ./fast_api
    restart: always
    env_file:
      - ./.env
    environment:
      - API_REDIS_HOST=redis
    ports:
      - '8000:8000'
    depends_on:
      - elasticsearch
      - redis

  redis:
    image: redis:7.0.9-alpine
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  elasticsearch_data:
